### ISSUE TITLE
Possible new issue with EXTDATA, list of models is not full

### ISSUE THREAD

**Issue by reyaz006** [ZombieAlex/mfcauto.py#7] opened 2018-03-12 14:56 UTC
Here is my problem:
I'm using this script https://github.com/beaston02/MFCRecorder and it relies on mfcauto.py.
Recently, I've found out that it doesn't record all models even though they are online.
Long story short, I think I've found why:
- When the script works, its FcwExtResp.php request returns ~1000 models.
- At the same time, if I open MFC in browser, I can see in debug window that its FcwExtResp.php request returned ~1500 models.

`respkey` and `serv` parameters differ between script and browser. I couldn't find what generated them.

**Comment by ZombieAlex** [comment] 2018-03-12 15:29
That's unlikely to be the cause. Those parameters values are supplied by the server and I'd expect them to be different for different clients.

I see that MFCRecorder is using query_user. So I'm inclined to think this is another example of ZombieAlex/MFCAuto#22. The same underlying server bug and the same proposed workaround would apply to mfcauto.py as well.

I haven't done much with the Python version of this package lately though, there could be a separate issue. Will run some more tests later this week as I get time.

**Comment by reyaz006** [comment] 2018-03-12 17:24
I don't think this issue has something to do with the bug on server and has any random nature. Because I can definitely reproduce the same situation at all times: with the script, the only FcwExtResp.php request returns ~1000 models, and with browser, one of three FcwExtResp.php requests returns ~1500 models (with the same format but with all the missing models).

I can understand something about different client id and different ways to use mfcauto. But I'm a bit lost with trying to understand the explanation from linked issue and ways to create a fix or workaround.

If I understand this right, it must be possible to send the same request in a way that would return all (~1500) models, the same way it's done in browser. But I didn't find any obvious environment property that should be different. I've now tried to insert my correct username:password instead of guest:guest in `client.py`, and it returns "Login failed" for some reason...

**Comment by ZombieAlex** [comment] 2018-03-12 18:24
I may be off base about the query_user. Only took the briefest glance at the MFCRecorder code. But if it's relying on query_user to determine if a model is online then that completely bypasses EXTDATA anyway.

For logging in, make sure you're using the hashed password. See [the Node documentation for that param](https://github.com/ZombieAlex/MFCAuto/blob/master/src/main/README.md#new-clientusername-password-options).

When you're comparing the results of the script and browser, are they both running on the same machine with the same IP address? In other words, have you ruled out that the script isn't getting fewer models because of region blocks.

**Comment by reyaz006** [comment] 2018-03-12 19:19
I feel stupid now. Yes, my browser happened to use proxy. Yes, if I disable proxy, I get those ~1000 models again. I've never thought there may be region blocks.

Is there any way to get around these? Or maybe it is possible to only use proxy for query_user to allow everything else to work directly? Should I create a separate issue about this or it's not worth it?

**Comment by ZombieAlex** [comment] 2018-03-13 01:59
On Linux you could use a tool like [proxychains](https://github.com/haad/proxychains) to have your entire Python process run through a proxy. I know that same tool also works on the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) (aka "Bash on Ubuntu on Windows"). And there are some similar tools for native Windows, although most of them are not free.

I probably wouldn't implement proxy functionality directly within mfcauto itself though.

Glad you figured out what you were seeing. I'll go ahead and close this out. Let me know if you have any other issues.

**Closed by ZombieAlex** 2018-03-13 01:59 UTC
